# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.3.1.dev157+g241937d.d20230224'
__version_tuple__ = version_tuple = (2, 3, 1, 'dev157', 'g241937d.d20230224')
