
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-05T22:36:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "add51fedf7543a2809a3a8c6108ab29a3c2f9336",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
