
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-03T10:03:29-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7889d24c591740020eced0e31376b9c0b30b8011",
 "version": "0.29.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
