# Generated by Django 3.2.16 on 2023-04-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devind_dictionaries', '0004_auto_20220421_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='parent_id',
            field=models.PositiveIntegerField(default=None, help_text='Parent identifier', null=True),
        ),
    ]
