from enum import Enum


class AdminRegisterLicenseResponse400Error(str, Enum):
    ERROR_INVALID_LICENSE = "ERROR_INVALID_LICENSE"
    ERROR_LICENSE_ALREADY_EXISTS = "ERROR_LICENSE_ALREADY_EXISTS"
    ERROR_LICENSE_HAS_EXPIRED = "ERROR_LICENSE_HAS_EXPIRED"
    ERROR_PREMIUM_LICENSE_INSTANCE_ID_MISMATCH = "ERROR_PREMIUM_LICENSE_INSTANCE_ID_MISMATCH"
    ERROR_UNSUPPORTED_LICENSE = "ERROR_UNSUPPORTED_LICENSE"

    def __str__(self) -> str:
        return str(self.value)
