from enum import Enum


class CreateDatabaseTableResponse400Error(str, Enum):
    ERROR_INITIAL_TABLE_DATA_HAS_DUPLICATE_NAMES = "ERROR_INITIAL_TABLE_DATA_HAS_DUPLICATE_NAMES"
    ERROR_INITIAL_TABLE_DATA_LIMIT_EXCEEDED = "ERROR_INITIAL_TABLE_DATA_LIMIT_EXCEEDED"
    ERROR_INVALID_BASEROW_FIELD_NAME = "ERROR_INVALID_BASEROW_FIELD_NAME"
    ERROR_INVALID_INITIAL_TABLE_DATA = "ERROR_INVALID_INITIAL_TABLE_DATA"
    ERROR_MAX_JOB_COUNT_EXCEEDED = "ERROR_MAX_JOB_COUNT_EXCEEDED"
    ERROR_REQUEST_BODY_VALIDATION = "ERROR_REQUEST_BODY_VALIDATION"
    ERROR_RESERVED_BASEROW_FIELD_NAME = "ERROR_RESERVED_BASEROW_FIELD_NAME"
    ERROR_USER_NOT_IN_GROUP = "ERROR_USER_NOT_IN_GROUP"

    def __str__(self) -> str:
        return str(self.value)
