from ..connection.base_connection import BaseCloudConnection as BaseCloudConnection
from _typeshed import Incomplete
from edgeiq.exceptions import ConnectionBlockedError as ConnectionBlockedError, PublishError as PublishError

ROUTING_KEY: Incomplete
RABBITMQ_HOST: Incomplete
RABBITMQ_PORT: Incomplete

class RabbitMQConnection(BaseCloudConnection):
    def __new__(cls): ...
    connection: Incomplete
    channel: Incomplete
    def __init__(self) -> None: ...
    def connect(self) -> None: ...
    def reconnect(self) -> None: ...
    def publish(self, message) -> None: ...
    def disconnect(self) -> None: ...
