
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-05T13:08:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "dded7d89ff03fafae8a9c93e093b6cc1d2e088ba",
 "version": "1.19.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
