
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-05T08:20:31-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f56a6aa2a6da6260b08bac9d0808f713f9bd129",
 "version": "2.0.0-beta1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
