# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class profileConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsprofileConfig(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = profileConfig()
        x.Init(buf, n + offset)
        return x

    # profileConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # profileConfig
    def DeviceAddress(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # profileConfig
    def InputBuffer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # profileConfig
    def OutputBuffer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # profileConfig
    def ProfileBasicData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.axisprofile.fbtypes.profile import profile
            obj = profile()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # profileConfig
    def InputMapping(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.axisprofile.fbtypes.valueMapping import valueMapping
            obj = valueMapping()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # profileConfig
    def OutputMapping(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.axisprofile.fbtypes.valueMapping import valueMapping
            obj = valueMapping()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # profileConfig
    def ScalingInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from comm.axisprofile.fbtypes.profileScalingCfg import profileScalingCfg
            obj = profileScalingCfg()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # profileConfig
    def DeviceName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def profileConfigStart(builder): builder.StartObject(8)
def profileConfigAddDeviceAddress(builder, deviceAddress): builder.PrependUint32Slot(0, deviceAddress, 0)
def profileConfigAddInputBuffer(builder, inputBuffer): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(inputBuffer), 0)
def profileConfigAddOutputBuffer(builder, outputBuffer): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(outputBuffer), 0)
def profileConfigAddProfileBasicData(builder, profileBasicData): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(profileBasicData), 0)
def profileConfigAddInputMapping(builder, inputMapping): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(inputMapping), 0)
def profileConfigAddOutputMapping(builder, outputMapping): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(outputMapping), 0)
def profileConfigAddScalingInfo(builder, scalingInfo): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(scalingInfo), 0)
def profileConfigAddDeviceName(builder, deviceName): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(deviceName), 0)
def profileConfigEnd(builder): return builder.EndObject()

import comm.axisprofile.fbtypes.profile
import comm.axisprofile.fbtypes.profileScalingCfg
import comm.axisprofile.fbtypes.valueMapping
try:
    from typing import Optional
except:
    pass

class profileConfigT(object):

    # profileConfigT
    def __init__(self):
        self.deviceAddress = 0  # type: int
        self.inputBuffer = None  # type: str
        self.outputBuffer = None  # type: str
        self.profileBasicData = None  # type: Optional[comm.axisprofile.fbtypes.profile.profileT]
        self.inputMapping = None  # type: Optional[comm.axisprofile.fbtypes.valueMapping.valueMappingT]
        self.outputMapping = None  # type: Optional[comm.axisprofile.fbtypes.valueMapping.valueMappingT]
        self.scalingInfo = None  # type: Optional[comm.axisprofile.fbtypes.profileScalingCfg.profileScalingCfgT]
        self.deviceName = None  # type: str

    @classmethod
    def InitFromBuf(cls, buf, pos):
        profileConfig = profileConfig()
        profileConfig.Init(buf, pos)
        return cls.InitFromObj(profileConfig)

    @classmethod
    def InitFromObj(cls, profileConfig):
        x = profileConfigT()
        x._UnPack(profileConfig)
        return x

    # profileConfigT
    def _UnPack(self, profileConfig):
        if profileConfig is None:
            return
        self.deviceAddress = profileConfig.DeviceAddress()
        self.inputBuffer = profileConfig.InputBuffer()
        self.outputBuffer = profileConfig.OutputBuffer()
        if profileConfig.ProfileBasicData() is not None:
            self.profileBasicData = comm.axisprofile.fbtypes.profile.profileT.InitFromObj(profileConfig.ProfileBasicData())
        if profileConfig.InputMapping() is not None:
            self.inputMapping = comm.axisprofile.fbtypes.valueMapping.valueMappingT.InitFromObj(profileConfig.InputMapping())
        if profileConfig.OutputMapping() is not None:
            self.outputMapping = comm.axisprofile.fbtypes.valueMapping.valueMappingT.InitFromObj(profileConfig.OutputMapping())
        if profileConfig.ScalingInfo() is not None:
            self.scalingInfo = comm.axisprofile.fbtypes.profileScalingCfg.profileScalingCfgT.InitFromObj(profileConfig.ScalingInfo())
        self.deviceName = profileConfig.DeviceName()

    # profileConfigT
    def Pack(self, builder):
        if self.inputBuffer is not None:
            inputBuffer = builder.CreateString(self.inputBuffer)
        if self.outputBuffer is not None:
            outputBuffer = builder.CreateString(self.outputBuffer)
        if self.profileBasicData is not None:
            profileBasicData = self.profileBasicData.Pack(builder)
        if self.inputMapping is not None:
            inputMapping = self.inputMapping.Pack(builder)
        if self.outputMapping is not None:
            outputMapping = self.outputMapping.Pack(builder)
        if self.scalingInfo is not None:
            scalingInfo = self.scalingInfo.Pack(builder)
        if self.deviceName is not None:
            deviceName = builder.CreateString(self.deviceName)
        profileConfigStart(builder)
        profileConfigAddDeviceAddress(builder, self.deviceAddress)
        if self.inputBuffer is not None:
            profileConfigAddInputBuffer(builder, inputBuffer)
        if self.outputBuffer is not None:
            profileConfigAddOutputBuffer(builder, outputBuffer)
        if self.profileBasicData is not None:
            profileConfigAddProfileBasicData(builder, profileBasicData)
        if self.inputMapping is not None:
            profileConfigAddInputMapping(builder, inputMapping)
        if self.outputMapping is not None:
            profileConfigAddOutputMapping(builder, outputMapping)
        if self.scalingInfo is not None:
            profileConfigAddScalingInfo(builder, scalingInfo)
        if self.deviceName is not None:
            profileConfigAddDeviceName(builder, deviceName)
        profileConfig = profileConfigEnd(builder)
        return profileConfig
