from enum import Enum


class Type9CbEnum(str, Enum):
    BOOLEAN = "boolean"
    CONTAINS = "contains"
    CONTAINS_NOT = "contains_not"
    CONTAINS_WORD = "contains_word"
    DATE_AFTER = "date_after"
    DATE_AFTER_TODAY = "date_after_today"
    DATE_BEFORE = "date_before"
    DATE_BEFORE_TODAY = "date_before_today"
    DATE_EQUAL = "date_equal"
    DATE_EQUALS_DAYS_AGO = "date_equals_days_ago"
    DATE_EQUALS_DAY_OF_MONTH = "date_equals_day_of_month"
    DATE_EQUALS_MONTH = "date_equals_month"
    DATE_EQUALS_MONTHS_AGO = "date_equals_months_ago"
    DATE_EQUALS_TODAY = "date_equals_today"
    DATE_EQUALS_WEEK = "date_equals_week"
    DATE_EQUALS_YEAR = "date_equals_year"
    DATE_EQUALS_YEARS_AGO = "date_equals_years_ago"
    DATE_NOT_EQUAL = "date_not_equal"
    DOESNT_CONTAIN_WORD = "doesnt_contain_word"
    EMPTY = "empty"
    EQUAL = "equal"
    FILENAME_CONTAINS = "filename_contains"
    HAS_FILE_TYPE = "has_file_type"
    HIGHER_THAN = "higher_than"
    LENGTH_IS_LOWER_THAN = "length_is_lower_than"
    LINK_ROW_CONTAINS = "link_row_contains"
    LINK_ROW_HAS = "link_row_has"
    LINK_ROW_HAS_NOT = "link_row_has_not"
    LINK_ROW_NOT_CONTAINS = "link_row_not_contains"
    LOWER_THAN = "lower_than"
    MULTIPLE_COLLABORATORS_HAS = "multiple_collaborators_has"
    MULTIPLE_COLLABORATORS_HAS_NOT = "multiple_collaborators_has_not"
    MULTIPLE_SELECT_HAS = "multiple_select_has"
    MULTIPLE_SELECT_HAS_NOT = "multiple_select_has_not"
    NOT_EMPTY = "not_empty"
    NOT_EQUAL = "not_equal"
    SINGLE_SELECT_EQUAL = "single_select_equal"
    SINGLE_SELECT_NOT_EQUAL = "single_select_not_equal"

    def __str__(self) -> str:
        return str(self.value)
