# Generated by Django 3.2 on 2022-12-08 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0003_topik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboard',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onboard.topik'),
        ),
    ]
