# coding: utf-8

"""
    RIME Rest API

    API methods for RIME. Must be authenticated with `rime-api-key` header.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: dev@robustintelligence.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpsertJobRequestWriteMaskJobData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stress': 'UpsertJobRequestWriteMaskJobDataStressTest',
        'continuous_inc': 'UpsertJobRequestWriteMaskJobDataContinuousIncrementalTest'
    }

    attribute_map = {
        'stress': 'stress',
        'continuous_inc': 'continuousInc'
    }

    def __init__(self, stress=None, continuous_inc=None):  # noqa: E501
        """UpsertJobRequestWriteMaskJobData - a model defined in Swagger"""  # noqa: E501
        self._stress = None
        self._continuous_inc = None
        self.discriminator = None
        if stress is not None:
            self.stress = stress
        if continuous_inc is not None:
            self.continuous_inc = continuous_inc

    @property
    def stress(self):
        """Gets the stress of this UpsertJobRequestWriteMaskJobData.  # noqa: E501


        :return: The stress of this UpsertJobRequestWriteMaskJobData.  # noqa: E501
        :rtype: UpsertJobRequestWriteMaskJobDataStressTest
        """
        return self._stress

    @stress.setter
    def stress(self, stress):
        """Sets the stress of this UpsertJobRequestWriteMaskJobData.


        :param stress: The stress of this UpsertJobRequestWriteMaskJobData.  # noqa: E501
        :type: UpsertJobRequestWriteMaskJobDataStressTest
        """

        self._stress = stress

    @property
    def continuous_inc(self):
        """Gets the continuous_inc of this UpsertJobRequestWriteMaskJobData.  # noqa: E501


        :return: The continuous_inc of this UpsertJobRequestWriteMaskJobData.  # noqa: E501
        :rtype: UpsertJobRequestWriteMaskJobDataContinuousIncrementalTest
        """
        return self._continuous_inc

    @continuous_inc.setter
    def continuous_inc(self, continuous_inc):
        """Sets the continuous_inc of this UpsertJobRequestWriteMaskJobData.


        :param continuous_inc: The continuous_inc of this UpsertJobRequestWriteMaskJobData.  # noqa: E501
        :type: UpsertJobRequestWriteMaskJobDataContinuousIncrementalTest
        """

        self._continuous_inc = continuous_inc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpsertJobRequestWriteMaskJobData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpsertJobRequestWriteMaskJobData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
