
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-05T12:39:46-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd03bc2cbc6697f3d19f716ef6a9103783f8a3fd",
 "version": "0.57.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
