#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['refpapers']

package_data = \
{'': ['*'],
 'refpapers': ['.mypy_cache/*',
               '.mypy_cache/3.8/*',
               '.mypy_cache/3.8/_typeshed/*',
               '.mypy_cache/3.8/asyncio/*',
               '.mypy_cache/3.8/attr/*',
               '.mypy_cache/3.8/click/*',
               '.mypy_cache/3.8/collections/*',
               '.mypy_cache/3.8/concurrent/*',
               '.mypy_cache/3.8/concurrent/futures/*',
               '.mypy_cache/3.8/ctypes/*',
               '.mypy_cache/3.8/dotenv/*',
               '.mypy_cache/3.8/email/*',
               '.mypy_cache/3.8/importlib/*',
               '.mypy_cache/3.8/json/*',
               '.mypy_cache/3.8/logging/*',
               '.mypy_cache/3.8/multiprocessing/*',
               '.mypy_cache/3.8/os/*',
               '.mypy_cache/3.8/prompt_toolkit/*',
               '.mypy_cache/3.8/prompt_toolkit/application/*',
               '.mypy_cache/3.8/prompt_toolkit/clipboard/*',
               '.mypy_cache/3.8/prompt_toolkit/completion/*',
               '.mypy_cache/3.8/prompt_toolkit/eventloop/*',
               '.mypy_cache/3.8/prompt_toolkit/filters/*',
               '.mypy_cache/3.8/prompt_toolkit/formatted_text/*',
               '.mypy_cache/3.8/prompt_toolkit/input/*',
               '.mypy_cache/3.8/prompt_toolkit/key_binding/*',
               '.mypy_cache/3.8/prompt_toolkit/key_binding/bindings/*',
               '.mypy_cache/3.8/prompt_toolkit/layout/*',
               '.mypy_cache/3.8/prompt_toolkit/lexers/*',
               '.mypy_cache/3.8/prompt_toolkit/output/*',
               '.mypy_cache/3.8/prompt_toolkit/shortcuts/*',
               '.mypy_cache/3.8/prompt_toolkit/shortcuts/progress_bar/*',
               '.mypy_cache/3.8/prompt_toolkit/styles/*',
               '.mypy_cache/3.8/prompt_toolkit/widgets/*',
               '.mypy_cache/3.8/pydantic/*',
               '.mypy_cache/3.8/pyexpat/*',
               '.mypy_cache/3.8/refpapers/*',
               '.mypy_cache/3.8/rich/*',
               '.mypy_cache/3.8/unidecode/*',
               '.mypy_cache/3.8/urllib/*',
               '.mypy_cache/3.8/xml/*',
               '.mypy_cache/3.8/xml/dom/*',
               '.mypy_cache/3.8/xml/parsers/*',
               '.mypy_cache/3.8/xml/parsers/expat/*',
               '.mypy_cache/3.8/xml/sax/*',
               '.mypy_cache/3.8/yaml/*',
               'htmlcov/*']}

install_requires = \
['Levenshtein==0.20.8',
 'PyYAML==5.4.1',
 'Unidecode==1.3.2',
 'arxiv==1.4.2',
 'click==8.0.1',
 'crossrefapi==1.5.0',
 'delegator.py==0.1.1',
 'prompt-toolkit==3.0.19',
 'pydantic==1.8.2',
 'rich==10.6.0',
 'scholarly==1.5.1',
 'whoosh==2.7.4']

entry_points = \
{'console_scripts': ['refpapers = refpapers:cli']}

setup(name='refpapers',
      version='1.1.0',
      description='refpapers - Manage and search bibliography from the command line',
      author='Stig-Arne Grönroos',
      author_email='stig.gronroos@gmail.com',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
