from enum import Enum


class CreateSnapshotResponse400Error(str, Enum):
    ERROR_APPLICATION_OPERATION_NOT_SUPPORTED = "ERROR_APPLICATION_OPERATION_NOT_SUPPORTED"
    ERROR_MAXIMUM_SNAPSHOTS_REACHED = "ERROR_MAXIMUM_SNAPSHOTS_REACHED"
    ERROR_SNAPSHOT_IS_BEING_CREATED = "ERROR_SNAPSHOT_IS_BEING_CREATED"
    ERROR_SNAPSHOT_NAME_NOT_UNIQUE = "ERROR_SNAPSHOT_NAME_NOT_UNIQUE"
    ERROR_SNAPSHOT_OPERATION_LIMIT_EXCEEDED = "ERROR_SNAPSHOT_OPERATION_LIMIT_EXCEEDED"
    ERROR_USER_NOT_IN_GROUP = "ERROR_USER_NOT_IN_GROUP"

    def __str__(self) -> str:
        return str(self.value)
