from enum import Enum


class ListDatabaseTableRowsResponse400Error(str, Enum):
    ERROR_FILTER_FIELD_NOT_FOUND = "ERROR_FILTER_FIELD_NOT_FOUND"
    ERROR_INVALID_PAGE = "ERROR_INVALID_PAGE"
    ERROR_ORDER_BY_FIELD_NOT_FOUND = "ERROR_ORDER_BY_FIELD_NOT_FOUND"
    ERROR_ORDER_BY_FIELD_NOT_POSSIBLE = "ERROR_ORDER_BY_FIELD_NOT_POSSIBLE"
    ERROR_PAGE_SIZE_LIMIT = "ERROR_PAGE_SIZE_LIMIT"
    ERROR_REQUEST_BODY_VALIDATION = "ERROR_REQUEST_BODY_VALIDATION"
    ERROR_USER_NOT_IN_GROUP = "ERROR_USER_NOT_IN_GROUP"
    ERROR_VIEW_FILTER_TYPE_DOES_NOT_EXIST = "ERROR_VIEW_FILTER_TYPE_DOES_NOT_EXIST"
    ERROR_VIEW_FILTER_TYPE_UNSUPPORTED_FIELD = "ERROR_VIEW_FILTER_TYPE_UNSUPPORTED_FIELD"

    def __str__(self) -> str:
        return str(self.value)
