# Generated by Django 3.2 on 2022-12-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0002_alter_onboarddet_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
