# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DcOnlineInfoResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDcOnlineInfoResponse(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DcOnlineInfoResponse()
        x.Init(buf, n + offset)
        return x

    # DcOnlineInfoResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DcOnlineInfoResponse
    def SyncMode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DcOnlineInfoResponse
    def CycleTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DcOnlineInfoResponse
    def SyncShiftTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DcOnlineInfoResponse
    def SyncWindowMonitoring(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # DcOnlineInfoResponse
    def DeviationLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DcOnlineInfoResponse
    def ContinuousDelayCompensation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # DcOnlineInfoResponse
    def SystemTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def DcOnlineInfoResponseStart(builder): builder.StartObject(7)
def DcOnlineInfoResponseAddSyncMode(builder, syncMode): builder.PrependUint32Slot(0, syncMode, 0)
def DcOnlineInfoResponseAddCycleTime(builder, cycleTime): builder.PrependUint32Slot(1, cycleTime, 0)
def DcOnlineInfoResponseAddSyncShiftTime(builder, syncShiftTime): builder.PrependUint32Slot(2, syncShiftTime, 0)
def DcOnlineInfoResponseAddSyncWindowMonitoring(builder, syncWindowMonitoring): builder.PrependBoolSlot(3, syncWindowMonitoring, 0)
def DcOnlineInfoResponseAddDeviationLimit(builder, deviationLimit): builder.PrependUint32Slot(4, deviationLimit, 0)
def DcOnlineInfoResponseAddContinuousDelayCompensation(builder, continuousDelayCompensation): builder.PrependBoolSlot(5, continuousDelayCompensation, 0)
def DcOnlineInfoResponseAddSystemTime(builder, systemTime): builder.PrependUint64Slot(6, systemTime, 0)
def DcOnlineInfoResponseEnd(builder): return builder.EndObject()


class DcOnlineInfoResponseT(object):

    # DcOnlineInfoResponseT
    def __init__(self):
        self.syncMode = 0  # type: int
        self.cycleTime = 0  # type: int
        self.syncShiftTime = 0  # type: int
        self.syncWindowMonitoring = False  # type: bool
        self.deviationLimit = 0  # type: int
        self.continuousDelayCompensation = False  # type: bool
        self.systemTime = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        dcOnlineInfoResponse = DcOnlineInfoResponse()
        dcOnlineInfoResponse.Init(buf, pos)
        return cls.InitFromObj(dcOnlineInfoResponse)

    @classmethod
    def InitFromObj(cls, dcOnlineInfoResponse):
        x = DcOnlineInfoResponseT()
        x._UnPack(dcOnlineInfoResponse)
        return x

    # DcOnlineInfoResponseT
    def _UnPack(self, dcOnlineInfoResponse):
        if dcOnlineInfoResponse is None:
            return
        self.syncMode = dcOnlineInfoResponse.SyncMode()
        self.cycleTime = dcOnlineInfoResponse.CycleTime()
        self.syncShiftTime = dcOnlineInfoResponse.SyncShiftTime()
        self.syncWindowMonitoring = dcOnlineInfoResponse.SyncWindowMonitoring()
        self.deviationLimit = dcOnlineInfoResponse.DeviationLimit()
        self.continuousDelayCompensation = dcOnlineInfoResponse.ContinuousDelayCompensation()
        self.systemTime = dcOnlineInfoResponse.SystemTime()

    # DcOnlineInfoResponseT
    def Pack(self, builder):
        DcOnlineInfoResponseStart(builder)
        DcOnlineInfoResponseAddSyncMode(builder, self.syncMode)
        DcOnlineInfoResponseAddCycleTime(builder, self.cycleTime)
        DcOnlineInfoResponseAddSyncShiftTime(builder, self.syncShiftTime)
        DcOnlineInfoResponseAddSyncWindowMonitoring(builder, self.syncWindowMonitoring)
        DcOnlineInfoResponseAddDeviationLimit(builder, self.deviationLimit)
        DcOnlineInfoResponseAddContinuousDelayCompensation(builder, self.continuousDelayCompensation)
        DcOnlineInfoResponseAddSystemTime(builder, self.systemTime)
        dcOnlineInfoResponse = DcOnlineInfoResponseEnd(builder)
        return dcOnlineInfoResponse
