# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MailboxStatisticResetResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMailboxStatisticResetResponse(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MailboxStatisticResetResponse()
        x.Init(buf, n + offset)
        return x

    # MailboxStatisticResetResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def MailboxStatisticResetResponseStart(builder): builder.StartObject(0)
def MailboxStatisticResetResponseEnd(builder): return builder.EndObject()


class MailboxStatisticResetResponseT(object):

    # MailboxStatisticResetResponseT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        mailboxStatisticResetResponse = MailboxStatisticResetResponse()
        mailboxStatisticResetResponse.Init(buf, pos)
        return cls.InitFromObj(mailboxStatisticResetResponse)

    @classmethod
    def InitFromObj(cls, mailboxStatisticResetResponse):
        x = MailboxStatisticResetResponseT()
        x._UnPack(mailboxStatisticResetResponse)
        return x

    # MailboxStatisticResetResponseT
    def _UnPack(self, mailboxStatisticResetResponse):
        if mailboxStatisticResetResponse is None:
            return

    # MailboxStatisticResetResponseT
    def Pack(self, builder):
        MailboxStatisticResetResponseStart(builder)
        mailboxStatisticResetResponse = MailboxStatisticResetResponseEnd(builder)
        return mailboxStatisticResetResponse
