# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ParameterResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsParameterResponse(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ParameterResponse()
        x.Init(buf, n + offset)
        return x

    # ParameterResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ParameterResponse
    def ElementFlags(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ParameterResponse
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ParameterResponse
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ParameterResponse
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ParameterResponse
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ParameterResponseStart(builder): builder.StartObject(2)
def ParameterResponseAddElementFlags(builder, elementFlags): builder.PrependUint8Slot(0, elementFlags, 0)
def ParameterResponseAddData(builder, data): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def ParameterResponseStartDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def ParameterResponseEnd(builder): return builder.EndObject()

try:
    from typing import List
except:
    pass

class ParameterResponseT(object):

    # ParameterResponseT
    def __init__(self):
        self.elementFlags = 0  # type: int
        self.data = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        parameterResponse = ParameterResponse()
        parameterResponse.Init(buf, pos)
        return cls.InitFromObj(parameterResponse)

    @classmethod
    def InitFromObj(cls, parameterResponse):
        x = ParameterResponseT()
        x._UnPack(parameterResponse)
        return x

    # ParameterResponseT
    def _UnPack(self, parameterResponse):
        if parameterResponse is None:
            return
        self.elementFlags = parameterResponse.ElementFlags()
        if not parameterResponse.DataIsNone():
            if np is None:
                self.data = []
                for i in range(parameterResponse.DataLength()):
                    self.data.append(parameterResponse.Data(i))
            else:
                self.data = parameterResponse.DataAsNumpy()

    # ParameterResponseT
    def Pack(self, builder):
        if self.data is not None:
            if np is not None and type(self.data) is np.ndarray:
                data = builder.CreateNumpyVector(self.data)
            else:
                ParameterResponseStartDataVector(builder, len(self.data))
                for i in reversed(range(len(self.data))):
                    builder.PrependUint8(self.data[i])
                data = builder.EndVector(len(self.data))
        ParameterResponseStart(builder)
        ParameterResponseAddElementFlags(builder, self.elementFlags)
        if self.data is not None:
            ParameterResponseAddData(builder, data)
        parameterResponse = ParameterResponseEnd(builder)
        return parameterResponse
