# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SlaveRegisterResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSlaveRegisterResponse(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SlaveRegisterResponse()
        x.Init(buf, n + offset)
        return x

    # SlaveRegisterResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SlaveRegisterResponse
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SlaveRegisterResponse
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SlaveRegisterResponse
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SlaveRegisterResponse
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SlaveRegisterResponseStart(builder): builder.StartObject(1)
def SlaveRegisterResponseAddData(builder, data): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def SlaveRegisterResponseStartDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def SlaveRegisterResponseEnd(builder): return builder.EndObject()

try:
    from typing import List
except:
    pass

class SlaveRegisterResponseT(object):

    # SlaveRegisterResponseT
    def __init__(self):
        self.data = None  # type: List[int]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        slaveRegisterResponse = SlaveRegisterResponse()
        slaveRegisterResponse.Init(buf, pos)
        return cls.InitFromObj(slaveRegisterResponse)

    @classmethod
    def InitFromObj(cls, slaveRegisterResponse):
        x = SlaveRegisterResponseT()
        x._UnPack(slaveRegisterResponse)
        return x

    # SlaveRegisterResponseT
    def _UnPack(self, slaveRegisterResponse):
        if slaveRegisterResponse is None:
            return
        if not slaveRegisterResponse.DataIsNone():
            if np is None:
                self.data = []
                for i in range(slaveRegisterResponse.DataLength()):
                    self.data.append(slaveRegisterResponse.Data(i))
            else:
                self.data = slaveRegisterResponse.DataAsNumpy()

    # SlaveRegisterResponseT
    def Pack(self, builder):
        if self.data is not None:
            if np is not None and type(self.data) is np.ndarray:
                data = builder.CreateNumpyVector(self.data)
            else:
                SlaveRegisterResponseStartDataVector(builder, len(self.data))
                for i in reversed(range(len(self.data))):
                    builder.PrependUint8(self.data[i])
                data = builder.EndVector(len(self.data))
        SlaveRegisterResponseStart(builder)
        if self.data is not None:
            SlaveRegisterResponseAddData(builder, data)
        slaveRegisterResponse = SlaveRegisterResponseEnd(builder)
        return slaveRegisterResponse
