def find_usb_device(id_vendor: int, id_product: int) -> bool: ...
def find_ncs2() -> bool: ...
def find_pcie_device(id_vendor: str, id_product: str) -> bool: ...
def find_hailo() -> bool: ...
def is_jetson() -> bool: ...
def is_jetson_nano() -> bool: ...
def is_jetson_xavier() -> bool: ...
def is_jetson_xavier_nx() -> bool: ...
def is_jetson_agx_xavier() -> bool: ...
def is_opencv_cuda_available() -> bool: ...
