# marginal tag assigner
COUNTS_DYNAMIC_RANGE = 50.0
MIN_COUNTS_PER_TAG = 1000
MAX_ALLOWED_PEARSON_CORRELATION = 0.5

# jibes tag assigner
DEFAULT_BLANK_PROB = 0.04
_MAX_K_LETS_TO_CONSIDER = 3
CORR_FACTOR = 1.54
NUM_TOTAL_TAGS = 14
JIBES_MIN_CONFIDENCE = 0.9

# general
N_G = 95000
G19_N_GEMS = {"MT": N_G, "LT": 9500, "HT": 190000}
MULTIPLETS_FACTOR_NAME = "Multiplet"
UNASSIGNED_FACTOR_NAME = "Unassigned"
BLANK_FACTOR_NAME = "Blanks"
ASSIGNMENT_COL_NAME = "Assignment"
ASSIGNMENT_PROB_COL_NAME = "Assignment_Probability"