from enum import Enum


class AssignRoleResponse404Error(str, Enum):
    ERROR_GROUP_DOES_NOT_EXIST = "ERROR_GROUP_DOES_NOT_EXIST"
    ERROR_OBJECT_SCOPE_TYPE_DOES_NOT_EXIST = "ERROR_OBJECT_SCOPE_TYPE_DOES_NOT_EXIST"
    ERROR_ROLE_DOES_NOT_EXIST = "ERROR_ROLE_DOES_NOT_EXIST"
    ERROR_SCOPE_DOES_NOT_EXIST = "ERROR_SCOPE_DOES_NOT_EXIST"
    ERROR_SUBJECT_TYPE_DOES_NOT_EXIST = "ERROR_SUBJECT_TYPE_DOES_NOT_EXIST"

    def __str__(self) -> str:
        return str(self.value)
