from enum import Enum


class RestoreResponse400Error(str, Enum):
    ERROR_CANNOT_RESTORE_PARENT_BEFORE_CHILD = "ERROR_CANNOT_RESTORE_PARENT_BEFORE_CHILD"
    ERROR_CANT_RESTORE_AS_RELATED_TABLE_TRASHED = "ERROR_CANT_RESTORE_AS_RELATED_TABLE_TRASHED"
    ERROR_PARENT_ID_MUST_BE_PROVIDED = "ERROR_PARENT_ID_MUST_BE_PROVIDED"
    ERROR_PARENT_ID_MUST_NOT_BE_PROVIDED = "ERROR_PARENT_ID_MUST_NOT_BE_PROVIDED"
    ERROR_TRASH_ITEM_DOES_NOT_EXIST = "ERROR_TRASH_ITEM_DOES_NOT_EXIST"
    ERROR_USER_NOT_IN_GROUP = "ERROR_USER_NOT_IN_GROUP"

    def __str__(self) -> str:
        return str(self.value)
