from enum import Enum


class UpdateBuilderPageResponse400Error(str, Enum):
    ERROR_PAGE_NAME_NOT_UNIQUE = "ERROR_PAGE_NAME_NOT_UNIQUE"
    ERROR_PAGE_PATH_NOT_UNIQUE = "ERROR_PAGE_PATH_NOT_UNIQUE"
    ERROR_PATH_PARAM_NOT_DEFINED = "ERROR_PATH_PARAM_NOT_DEFINED"
    ERROR_PATH_PARAM_NOT_IN_PATH = "ERROR_PATH_PARAM_NOT_IN_PATH"
    ERROR_REQUEST_BODY_VALIDATION = "ERROR_REQUEST_BODY_VALIDATION"

    def __str__(self) -> str:
        return str(self.value)
