"""
    Bamboo Flexibility API

     This API provides access to flexibility assets managed by Bamboo Energy: - Create and list flexibility sites & assets - Obtain activations for specific assets - Post and get measurements for specific assets   # noqa: E501

    The version of the OpenAPI document: 1.18.7
    Contact: development@bambooenergy.tech
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from bambooapi_client.openapi.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from bambooapi_client.openapi.exceptions import ApiAttributeError



class DeviceActivationListItem(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('humidity',): {
            'inclusive_maximum': 100,
            'inclusive_minimum': 0,
        },
        ('luxsp',): {
            'inclusive_maximum': 10000,
            'inclusive_minimum': 0,
        },
        ('mode',): {
            'max_length': 20,
            'min_length': 2,
        },
        ('power',): {
            'inclusive_maximum': 1000000,
            'inclusive_minimum': -1000000,
        },
        ('powersp',): {
            'inclusive_maximum': 1000000,
            'inclusive_minimum': -1000000,
        },
        ('soc',): {
            'inclusive_maximum': 100,
            'inclusive_minimum': 0,
        },
        ('temp',): {
            'inclusive_maximum': 100,
            'inclusive_minimum': -100,
        },
        ('tempsp',): {
            'inclusive_maximum': 100,
            'inclusive_minimum': -100,
        },
        ('vref',): {
            'inclusive_maximum': 100,
            'inclusive_minimum': 0,
        },
        ('deltatempsp',): {
            'inclusive_maximum': 10,
            'inclusive_minimum': -10,
        },
        ('volsp',): {
            'inclusive_maximum': 1000000,
            'inclusive_minimum': 0,
        },
        ('deltavolsp',): {
            'inclusive_maximum': 1000000,
            'inclusive_minimum': -1000000,
        },
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'start_time': (datetime,),  # noqa: E501
            'device_name': (str,),  # noqa: E501
            'humidity': (float,),  # noqa: E501
            'luxsp': (int,),  # noqa: E501
            'mode': (str,),  # noqa: E501
            'power': (float,),  # noqa: E501
            'powersp': (float,),  # noqa: E501
            'schedule': (bool,),  # noqa: E501
            'soc': (float,),  # noqa: E501
            'status': (bool,),  # noqa: E501
            'temp': (float,),  # noqa: E501
            'tempsp': (float,),  # noqa: E501
            'vref': (int,),  # noqa: E501
            'deltatempsp': (float,),  # noqa: E501
            'volsp': (float,),  # noqa: E501
            'deltavolsp': (float,),  # noqa: E501
            'end_time': (datetime,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'start_time': 'start_time',  # noqa: E501
        'device_name': 'device_name',  # noqa: E501
        'humidity': 'humidity',  # noqa: E501
        'luxsp': 'luxsp',  # noqa: E501
        'mode': 'mode',  # noqa: E501
        'power': 'power',  # noqa: E501
        'powersp': 'powersp',  # noqa: E501
        'schedule': 'schedule',  # noqa: E501
        'soc': 'soc',  # noqa: E501
        'status': 'status',  # noqa: E501
        'temp': 'temp',  # noqa: E501
        'tempsp': 'tempsp',  # noqa: E501
        'vref': 'vref',  # noqa: E501
        'deltatempsp': 'deltatempsp',  # noqa: E501
        'volsp': 'volsp',  # noqa: E501
        'deltavolsp': 'deltavolsp',  # noqa: E501
        'end_time': 'end_time',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, start_time, device_name, *args, **kwargs):  # noqa: E501
        """DeviceActivationListItem - a model defined in OpenAPI

        Args:
            start_time (datetime):
            device_name (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            humidity (float): %. [optional]  # noqa: E501
            luxsp (int): lux. [optional]  # noqa: E501
            mode (str): [optional]  # noqa: E501
            power (float): kW. [optional]  # noqa: E501
            powersp (float): kW. [optional]  # noqa: E501
            schedule (bool): [optional]  # noqa: E501
            soc (float): %. [optional]  # noqa: E501
            status (bool): [optional]  # noqa: E501
            temp (float): ºC. [optional]  # noqa: E501
            tempsp (float): ºC. [optional]  # noqa: E501
            vref (int): %. [optional]  # noqa: E501
            deltatempsp (float): ºC. [optional]  # noqa: E501
            volsp (float): l. [optional]  # noqa: E501
            deltavolsp (float): l. [optional]  # noqa: E501
            end_time (datetime): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.start_time = start_time
        self.device_name = device_name
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, start_time, device_name, *args, **kwargs):  # noqa: E501
        """DeviceActivationListItem - a model defined in OpenAPI

        Args:
            start_time (datetime):
            device_name (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            humidity (float): %. [optional]  # noqa: E501
            luxsp (int): lux. [optional]  # noqa: E501
            mode (str): [optional]  # noqa: E501
            power (float): kW. [optional]  # noqa: E501
            powersp (float): kW. [optional]  # noqa: E501
            schedule (bool): [optional]  # noqa: E501
            soc (float): %. [optional]  # noqa: E501
            status (bool): [optional]  # noqa: E501
            temp (float): ºC. [optional]  # noqa: E501
            tempsp (float): ºC. [optional]  # noqa: E501
            vref (int): %. [optional]  # noqa: E501
            deltatempsp (float): ºC. [optional]  # noqa: E501
            volsp (float): l. [optional]  # noqa: E501
            deltavolsp (float): l. [optional]  # noqa: E501
            end_time (datetime): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.start_time = start_time
        self.device_name = device_name
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
