# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Cmd_AxsPower(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCmd_AxsPower(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Cmd_AxsPower()
        x.Init(buf, n + offset)
        return x

    # Cmd_AxsPower
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Cmd_AxsPower
    def Base(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from script.manager.fbtypes.Cmd_Base import Cmd_Base
            obj = Cmd_Base()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Cmd_AxsPower
    def SwitchOn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Cmd_AxsPowerStart(builder): builder.StartObject(2)
def Cmd_AxsPowerAddBase(builder, base): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(base), 0)
def Cmd_AxsPowerAddSwitchOn(builder, switchOn): builder.PrependBoolSlot(1, switchOn, 0)
def Cmd_AxsPowerEnd(builder): return builder.EndObject()

import script.manager.fbtypes.Cmd_Base
try:
    from typing import Optional
except:
    pass

class Cmd_AxsPowerT(object):

    # Cmd_AxsPowerT
    def __init__(self):
        self.base = None  # type: Optional[script.manager.fbtypes.Cmd_Base.Cmd_BaseT]
        self.switchOn = False  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        cmdAxsPower = Cmd_AxsPower()
        cmdAxsPower.Init(buf, pos)
        return cls.InitFromObj(cmdAxsPower)

    @classmethod
    def InitFromObj(cls, cmdAxsPower):
        x = Cmd_AxsPowerT()
        x._UnPack(cmdAxsPower)
        return x

    # Cmd_AxsPowerT
    def _UnPack(self, cmdAxsPower):
        if cmdAxsPower is None:
            return
        if cmdAxsPower.Base() is not None:
            self.base = script.manager.fbtypes.Cmd_Base.Cmd_BaseT.InitFromObj(cmdAxsPower.Base())
        self.switchOn = cmdAxsPower.SwitchOn()

    # Cmd_AxsPowerT
    def Pack(self, builder):
        if self.base is not None:
            base = self.base.Pack(builder)
        Cmd_AxsPowerStart(builder)
        if self.base is not None:
            Cmd_AxsPowerAddBase(builder, base)
        Cmd_AxsPowerAddSwitchOn(builder, self.switchOn)
        cmdAxsPower = Cmd_AxsPowerEnd(builder)
        return cmdAxsPower
