from enum import Enum


class CreateDatabaseTableViewSortResponse400Error(str, Enum):
    ERROR_FIELD_NOT_IN_TABLE = "ERROR_FIELD_NOT_IN_TABLE"
    ERROR_REQUEST_BODY_VALIDATION = "ERROR_REQUEST_BODY_VALIDATION"
    ERROR_USER_NOT_IN_GROUP = "ERROR_USER_NOT_IN_GROUP"
    ERROR_VIEW_SORT_FIELD_ALREADY_EXISTS = "ERROR_VIEW_SORT_FIELD_ALREADY_EXISTS"
    ERROR_VIEW_SORT_FIELD_NOT_SUPPORTED = "ERROR_VIEW_SORT_FIELD_NOT_SUPPORTED"
    ERROR_VIEW_SORT_NOT_SUPPORTED = "ERROR_VIEW_SORT_NOT_SUPPORTED"

    def __str__(self) -> str:
        return str(self.value)
