from enum import Enum


class ListDatabaseTableKanbanViewRowsResponse400Error(str, Enum):
    ERROR_FEATURE_NOT_AVAILABLE = "ERROR_FEATURE_NOT_AVAILABLE"
    ERROR_INVALID_SELECT_OPTION_PARAMETER = "ERROR_INVALID_SELECT_OPTION_PARAMETER"
    ERROR_KANBAN_VIEW_HAS_NO_SINGLE_SELECT_FIELD = "ERROR_KANBAN_VIEW_HAS_NO_SINGLE_SELECT_FIELD"
    ERROR_USER_NOT_IN_GROUP = "ERROR_USER_NOT_IN_GROUP"

    def __str__(self) -> str:
        return str(self.value)
