from enum import Enum


class UpdateDatabaseTableFieldResponse400Error(str, Enum):
    ERROR_CANNOT_CHANGE_FIELD_TYPE = "ERROR_CANNOT_CHANGE_FIELD_TYPE"
    ERROR_FIELD_CIRCULAR_REFERENCE = "ERROR_FIELD_CIRCULAR_REFERENCE"
    ERROR_FIELD_SELF_REFERENCE = "ERROR_FIELD_SELF_REFERENCE"
    ERROR_FIELD_WITH_SAME_NAME_ALREADY_EXISTS = "ERROR_FIELD_WITH_SAME_NAME_ALREADY_EXISTS"
    ERROR_INVALID_BASEROW_FIELD_NAME = "ERROR_INVALID_BASEROW_FIELD_NAME"
    ERROR_REQUEST_BODY_VALIDATION = "ERROR_REQUEST_BODY_VALIDATION"
    ERROR_RESERVED_BASEROW_FIELD_NAME = "ERROR_RESERVED_BASEROW_FIELD_NAME"
    ERROR_USER_NOT_IN_GROUP = "ERROR_USER_NOT_IN_GROUP"

    def __str__(self) -> str:
        return str(self.value)
