# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from circle import schemas  # noqa: F401


class Ach(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "routingNumber",
            "metadata",
            "updateDate",
            "billingDetails",
            "fingerprint",
            "description",
            "id",
            "accountNumber",
            "bankAddress",
            "createDate",
        }
        
        class properties:
            id = schemas.UUIDSchema
            accountNumber = schemas.StrSchema
            routingNumber = schemas.StrSchema
        
            @staticmethod
            def billingDetails() -> typing.Type['AchBillingDetails']:
                return AchBillingDetails
        
            @staticmethod
            def bankAddress() -> typing.Type['BankAddress']:
                return BankAddress
            fingerprint = schemas.StrSchema
            createDate = schemas.StrSchema
            updateDate = schemas.StrSchema
        
            @staticmethod
            def metadata() -> typing.Type['MetadataPhoneEmail']:
                return MetadataPhoneEmail
        
            @staticmethod
            def status() -> typing.Type['ExternalFiatAccountStatus']:
                return ExternalFiatAccountStatus
        
            @staticmethod
            def bankAccountType() -> typing.Type['AchAccountType']:
                return AchAccountType
        
            @staticmethod
            def errorCode() -> typing.Type['AchVerificationErrorCodes']:
                return AchVerificationErrorCodes
        
            @staticmethod
            def riskEvaluation() -> typing.Type['RiskEvaluation']:
                return RiskEvaluation
            __annotations__ = {
                "id": id,
                "accountNumber": accountNumber,
                "routingNumber": routingNumber,
                "billingDetails": billingDetails,
                "bankAddress": bankAddress,
                "fingerprint": fingerprint,
                "createDate": createDate,
                "updateDate": updateDate,
                "metadata": metadata,
                "status": status,
                "bankAccountType": bankAccountType,
                "errorCode": errorCode,
                "riskEvaluation": riskEvaluation,
            }
    
    routingNumber: MetaOapg.properties.routingNumber
    metadata: 'MetadataPhoneEmail'
    updateDate: MetaOapg.properties.updateDate
    billingDetails: 'AchBillingDetails'
    fingerprint: MetaOapg.properties.fingerprint
    description: schemas.AnyTypeSchema
    id: MetaOapg.properties.id
    accountNumber: MetaOapg.properties.accountNumber
    bankAddress: 'BankAddress'
    createDate: MetaOapg.properties.createDate
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["accountNumber"]) -> MetaOapg.properties.accountNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["routingNumber"]) -> MetaOapg.properties.routingNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["billingDetails"]) -> 'AchBillingDetails': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bankAddress"]) -> 'BankAddress': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fingerprint"]) -> MetaOapg.properties.fingerprint: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createDate"]) -> MetaOapg.properties.createDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updateDate"]) -> MetaOapg.properties.updateDate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> 'MetadataPhoneEmail': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> 'ExternalFiatAccountStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bankAccountType"]) -> 'AchAccountType': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["errorCode"]) -> 'AchVerificationErrorCodes': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["riskEvaluation"]) -> 'RiskEvaluation': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "accountNumber", "routingNumber", "billingDetails", "bankAddress", "fingerprint", "createDate", "updateDate", "metadata", "status", "bankAccountType", "errorCode", "riskEvaluation", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["accountNumber"]) -> MetaOapg.properties.accountNumber: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["routingNumber"]) -> MetaOapg.properties.routingNumber: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["billingDetails"]) -> 'AchBillingDetails': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bankAddress"]) -> 'BankAddress': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fingerprint"]) -> MetaOapg.properties.fingerprint: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createDate"]) -> MetaOapg.properties.createDate: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updateDate"]) -> MetaOapg.properties.updateDate: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> 'MetadataPhoneEmail': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union['ExternalFiatAccountStatus', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bankAccountType"]) -> typing.Union['AchAccountType', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["errorCode"]) -> typing.Union['AchVerificationErrorCodes', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["riskEvaluation"]) -> typing.Union['RiskEvaluation', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "accountNumber", "routingNumber", "billingDetails", "bankAddress", "fingerprint", "createDate", "updateDate", "metadata", "status", "bankAccountType", "errorCode", "riskEvaluation", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        routingNumber: typing.Union[MetaOapg.properties.routingNumber, str, ],
        metadata: 'MetadataPhoneEmail',
        updateDate: typing.Union[MetaOapg.properties.updateDate, str, ],
        billingDetails: 'AchBillingDetails',
        fingerprint: typing.Union[MetaOapg.properties.fingerprint, str, ],
        description: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        id: typing.Union[MetaOapg.properties.id, str, uuid.UUID, ],
        accountNumber: typing.Union[MetaOapg.properties.accountNumber, str, ],
        bankAddress: 'BankAddress',
        createDate: typing.Union[MetaOapg.properties.createDate, str, ],
        status: typing.Union['ExternalFiatAccountStatus', schemas.Unset] = schemas.unset,
        bankAccountType: typing.Union['AchAccountType', schemas.Unset] = schemas.unset,
        errorCode: typing.Union['AchVerificationErrorCodes', schemas.Unset] = schemas.unset,
        riskEvaluation: typing.Union['RiskEvaluation', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Ach':
        return super().__new__(
            cls,
            *_args,
            routingNumber=routingNumber,
            metadata=metadata,
            updateDate=updateDate,
            billingDetails=billingDetails,
            fingerprint=fingerprint,
            description=description,
            id=id,
            accountNumber=accountNumber,
            bankAddress=bankAddress,
            createDate=createDate,
            status=status,
            bankAccountType=bankAccountType,
            errorCode=errorCode,
            riskEvaluation=riskEvaluation,
            _configuration=_configuration,
            **kwargs,
        )

from circle.model.ach_account_type import AchAccountType
from circle.model.ach_billing_details import AchBillingDetails
from circle.model.ach_verification_error_codes import AchVerificationErrorCodes
from circle.model.bank_address import BankAddress
from circle.model.external_fiat_account_status import ExternalFiatAccountStatus
from circle.model.metadata_phone_email import MetadataPhoneEmail
from circle.model.risk_evaluation import RiskEvaluation
