# coding: utf-8

"""
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from circle import schemas  # noqa: F401


class MetadataPayout(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Additional properties related to the payout beneficiary.
    """


    class MetaOapg:
        required = {
            "beneficiaryEmail",
        }
        
        class properties:
        
            @staticmethod
            def beneficiaryEmail() -> typing.Type['Email']:
                return Email
            __annotations__ = {
                "beneficiaryEmail": beneficiaryEmail,
            }
    
    beneficiaryEmail: 'Email'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["beneficiaryEmail"]) -> 'Email': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["beneficiaryEmail", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["beneficiaryEmail"]) -> 'Email': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["beneficiaryEmail", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        beneficiaryEmail: 'Email',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MetadataPayout':
        return super().__new__(
            cls,
            *_args,
            beneficiaryEmail=beneficiaryEmail,
            _configuration=_configuration,
            **kwargs,
        )

from circle.model.email import Email
