
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-04T12:48:22+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "139ddd5eca8f5a43f23a10ca09b4e0e224cdb1c5",
 "version": "0.2.65"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
