from enum import Enum


class UpdateDatabaseTokenResponse400Error(str, Enum):
    ERROR_DATABASE_DOES_NOT_BELONG_TO_GROUP = "ERROR_DATABASE_DOES_NOT_BELONG_TO_GROUP"
    ERROR_REQUEST_BODY_VALIDATION = "ERROR_REQUEST_BODY_VALIDATION"
    ERROR_TABLE_DOES_NOT_BELONG_TO_GROUP = "ERROR_TABLE_DOES_NOT_BELONG_TO_GROUP"
    ERROR_USER_NOT_IN_GROUP = "ERROR_USER_NOT_IN_GROUP"

    def __str__(self) -> str:
        return str(self.value)
