from enum import Enum


class ExportTableResponse400Error(str, Enum):
    ERROR_REQUEST_BODY_VALIDATION = "ERROR_REQUEST_BODY_VALIDATION"
    ERROR_TABLE_ONLY_EXPORT_UNSUPPORTED = "ERROR_TABLE_ONLY_EXPORT_UNSUPPORTED"
    ERROR_USER_NOT_IN_GROUP = "ERROR_USER_NOT_IN_GROUP"
    ERROR_VIEW_NOT_IN_TABLE = "ERROR_VIEW_NOT_IN_TABLE"
    ERROR_VIEW_UNSUPPORTED_FOR_EXPORT_TYPE = "ERROR_VIEW_UNSUPPORTED_FOR_EXPORT_TYPE"

    def __str__(self) -> str:
        return str(self.value)
