
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-06T14:45:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8b975518d142b0205f8b5820bc90d58c49b9c0d",
 "version": "2.9.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
