# automatically generated by the FlatBuffers compiler, do not modify

# namespace: datalayer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Int16(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInt16(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Int16()
        x.Init(buf, n + offset)
        return x

    # Int16
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Int16
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

def Int16Start(builder): builder.StartObject(1)
def Int16AddValue(builder, value): builder.PrependInt16Slot(0, value, 0)
def Int16End(builder): return builder.EndObject()


class Int16T(object):

    # Int16T
    def __init__(self):
        self.value = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        int16 = Int16()
        int16.Init(buf, pos)
        return cls.InitFromObj(int16)

    @classmethod
    def InitFromObj(cls, int16):
        x = Int16T()
        x._UnPack(int16)
        return x

    # Int16T
    def _UnPack(self, int16):
        if int16 is None:
            return
        self.value = int16.Value()

    # Int16T
    def Pack(self, builder):
        Int16Start(builder)
        Int16AddValue(builder, self.value)
        int16 = Int16End(builder)
        return int16
