# Generated by Django 2.2.28 on 2023-04-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_tzcld', '0016_tzcldcontactmember'),
        ('djangoldp_tzcld', '0015_auto_20230330_1439'),
    ]

    operations = [
    ]
