# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# configuration for reaction to device error
class AxsCfgDeviceErrorReaction(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAxsCfgDeviceErrorReaction(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AxsCfgDeviceErrorReaction()
        x.Init(buf, n + offset)
        return x

    # AxsCfgDeviceErrorReaction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # user E-Stop dynamic limitations
    # AxsCfgDeviceErrorReaction
    def UserEstopLim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from motion.core.fbtypes.AxsCfgEstopDynamicLimits import AxsCfgEstopDynamicLimits
            obj = AxsCfgEstopDynamicLimits()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # E-Stop setting to different device errors
    # AxsCfgDeviceErrorReaction
    def EstopSettings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from motion.core.fbtypes.AxsCfgEstopSettings import AxsCfgEstopSettings
            obj = AxsCfgEstopSettings()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AxsCfgDeviceErrorReactionStart(builder): builder.StartObject(2)
def AxsCfgDeviceErrorReactionAddUserEstopLim(builder, userEstopLim): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(userEstopLim), 0)
def AxsCfgDeviceErrorReactionAddEstopSettings(builder, estopSettings): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(estopSettings), 0)
def AxsCfgDeviceErrorReactionEnd(builder): return builder.EndObject()

import motion.core.fbtypes.AxsCfgEstopDynamicLimits
import motion.core.fbtypes.AxsCfgEstopSettings
try:
    from typing import Optional
except:
    pass

class AxsCfgDeviceErrorReactionT(object):

    # AxsCfgDeviceErrorReactionT
    def __init__(self):
        self.userEstopLim = None  # type: Optional[motion.core.fbtypes.AxsCfgEstopDynamicLimits.AxsCfgEstopDynamicLimitsT]
        self.estopSettings = None  # type: Optional[motion.core.fbtypes.AxsCfgEstopSettings.AxsCfgEstopSettingsT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        axsCfgDeviceErrorReaction = AxsCfgDeviceErrorReaction()
        axsCfgDeviceErrorReaction.Init(buf, pos)
        return cls.InitFromObj(axsCfgDeviceErrorReaction)

    @classmethod
    def InitFromObj(cls, axsCfgDeviceErrorReaction):
        x = AxsCfgDeviceErrorReactionT()
        x._UnPack(axsCfgDeviceErrorReaction)
        return x

    # AxsCfgDeviceErrorReactionT
    def _UnPack(self, axsCfgDeviceErrorReaction):
        if axsCfgDeviceErrorReaction is None:
            return
        if axsCfgDeviceErrorReaction.UserEstopLim() is not None:
            self.userEstopLim = motion.core.fbtypes.AxsCfgEstopDynamicLimits.AxsCfgEstopDynamicLimitsT.InitFromObj(axsCfgDeviceErrorReaction.UserEstopLim())
        if axsCfgDeviceErrorReaction.EstopSettings() is not None:
            self.estopSettings = motion.core.fbtypes.AxsCfgEstopSettings.AxsCfgEstopSettingsT.InitFromObj(axsCfgDeviceErrorReaction.EstopSettings())

    # AxsCfgDeviceErrorReactionT
    def Pack(self, builder):
        if self.userEstopLim is not None:
            userEstopLim = self.userEstopLim.Pack(builder)
        if self.estopSettings is not None:
            estopSettings = self.estopSettings.Pack(builder)
        AxsCfgDeviceErrorReactionStart(builder)
        if self.userEstopLim is not None:
            AxsCfgDeviceErrorReactionAddUserEstopLim(builder, userEstopLim)
        if self.estopSettings is not None:
            AxsCfgDeviceErrorReactionAddEstopSettings(builder, estopSettings)
        axsCfgDeviceErrorReaction = AxsCfgDeviceErrorReactionEnd(builder)
        return axsCfgDeviceErrorReaction
