# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fbtypes

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FeedGroupSettings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFeedGroupSettings(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FeedGroupSettings()
        x.Init(buf, n + offset)
        return x

    # FeedGroupSettings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FeedGroupSettings
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def FeedGroupSettingsStart(builder): builder.StartObject(1)
def FeedGroupSettingsAddType(builder, type): builder.PrependInt8Slot(0, type, 0)
def FeedGroupSettingsEnd(builder): return builder.EndObject()


class FeedGroupSettingsT(object):

    # FeedGroupSettingsT
    def __init__(self):
        self.type = 0  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        feedGroupSettings = FeedGroupSettings()
        feedGroupSettings.Init(buf, pos)
        return cls.InitFromObj(feedGroupSettings)

    @classmethod
    def InitFromObj(cls, feedGroupSettings):
        x = FeedGroupSettingsT()
        x._UnPack(feedGroupSettings)
        return x

    # FeedGroupSettingsT
    def _UnPack(self, feedGroupSettings):
        if feedGroupSettings is None:
            return
        self.type = feedGroupSettings.Type()

    # FeedGroupSettingsT
    def Pack(self, builder):
        FeedGroupSettingsStart(builder)
        FeedGroupSettingsAddType(builder, self.type)
        feedGroupSettings = FeedGroupSettingsEnd(builder)
        return feedGroupSettings
