
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-05T04:21:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bfad00b7c917319423c911cb0372a6b38a5431d",
 "version": "1.18.3.post0.dev19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
