# flake8: noqa

"""
    Bamboo Flexibility API

     This API provides access to flexibility assets managed by Bamboo Energy: - Create and list flexibility sites & assets - Obtain activations for specific assets - Post and get measurements for specific assets   # noqa: E501

    The version of the OpenAPI document: 1.18.7
    Contact: development@bambooenergy.tech
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from bambooapi_client.openapi.api_client import ApiClient

# import Configuration
from bambooapi_client.openapi.configuration import Configuration

# import exceptions
from bambooapi_client.openapi.exceptions import OpenApiException
from bambooapi_client.openapi.exceptions import ApiAttributeError
from bambooapi_client.openapi.exceptions import ApiTypeError
from bambooapi_client.openapi.exceptions import ApiValueError
from bambooapi_client.openapi.exceptions import ApiKeyError
from bambooapi_client.openapi.exceptions import ApiException
