# coding: utf-8

"""
    Martlet Organization API

    Create/maintain organizations, access keys, addresses and permissions.   # noqa: E501

    OpenAPI spec version: 0.118.0
    Contact: apiteam@bmbix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bmb_martlet_organization_client
from bmb_martlet_organization_client.api.access_lists_api import AccessListsApi  # noqa: E501
from bmb_martlet_organization_client.rest import ApiException


class TestAccessListsApi(unittest.TestCase):
    """AccessListsApi unit test stubs"""

    def setUp(self):
        self.api = AccessListsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_list(self):
        """Test case for activate_list

        \"create an activation record for this list. Removes any other list's activation record.\"   # noqa: E501
        """
        pass

    def test_add_entry(self):
        """Test case for add_entry

        Add an entry to an access list  # noqa: E501
        """
        pass

    def test_add_list(self):
        """Test case for add_list

        Add an access list  # noqa: E501
        """
        pass

    def test_deactivate_list(self):
        """Test case for deactivate_list

        Delete an activation  # noqa: E501
        """
        pass

    def test_delete_entry(self):
        """Test case for delete_entry

        Delete an access list entry  # noqa: E501
        """
        pass

    def test_delete_list(self):
        """Test case for delete_list

        Delete a list  # noqa: E501
        """
        pass

    def test_get_entries(self):
        """Test case for get_entries

        Get list entries  # noqa: E501
        """
        pass

    def test_get_list(self):
        """Test case for get_list

        get single access list for owner  # noqa: E501
        """
        pass

    def test_get_lists(self):
        """Test case for get_lists

        get access lists for owner  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
