
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-07T17:51:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2804d333b199f7e81b844bfad0c4a62efe630c4c",
 "version": "2.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
