# coding: utf-8

"""
    Martlet Organization API

    Create/maintain organizations, access keys, addresses and permissions.   # noqa: E501

    OpenAPI spec version: 0.122.0
    Contact: apiteam@bmbix.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import bmb_martlet_organization_client
from bmb_martlet_organization_client.api.organization_proxies_api import OrganizationProxiesApi  # noqa: E501
from bmb_martlet_organization_client.rest import ApiException


class TestOrganizationProxiesApi(unittest.TestCase):
    """OrganizationProxiesApi unit test stubs"""

    def setUp(self):
        self.api = OrganizationProxiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        [create] Create an organization proxy.  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        [delete] Delete a proxy.  # noqa: E501
        """
        pass

    def test_get_proxies(self):
        """Test case for get_proxies

        [get_proxies ] Returns the proxies for this organization.  # noqa: E501
        """
        pass

    def test_get_proxy(self):
        """Test case for get_proxy

        [get_proxy] Get details of an individual proxy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
